[package]
name = "advent2021"
version = "0.1.0"
authors = ["Sam Raker <sam.raker@gmail.com>"]
edition = "2018"


[lib]
name = "advent2021"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
